package com.auto.jaxws.cxf.model;

// Generated Oct 12, 2014 11:01:48 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Autointerrior generated by hbm2java
 */
public class Autointerrior implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int autointerriorid;
	private String autointerriorname;
	private Set<Auto> autos = new HashSet<Auto>(0);

	public Autointerrior() {
	}

	public Autointerrior(int autointerriorid) {
		this.autointerriorid = autointerriorid;
	}

	public Autointerrior(int autointerriorid, String autointerriorname,
			Set<Auto> autos) {
		this.autointerriorid = autointerriorid;
		this.autointerriorname = autointerriorname;
		this.autos = autos;
	}

	public int getAutointerriorid() {
		return this.autointerriorid;
	}

	public void setAutointerriorid(int autointerriorid) {
		this.autointerriorid = autointerriorid;
	}

	public String getAutointerriorname() {
		return this.autointerriorname;
	}

	public void setAutointerriorname(String autointerriorname) {
		this.autointerriorname = autointerriorname;
	}

	public Set<Auto> getAutos() {
		return this.autos;
	}

	public void setAutos(Set<Auto> autos) {
		this.autos = autos;
	}

}
