package com.auto.jaxws.cxf.model;

// Generated Nov 16, 2014 1:40:49 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Autogear generated by hbm2java
 */
@Entity
@Table(name = "autogear", schema = "public")
public class Autogear implements java.io.Serializable {

	private int autogearid;
	private String autogearname;
	private Set<Auto> autos = new HashSet<Auto>(0);

	public Autogear() {
	}

	public Autogear(int autogearid) {
		this.autogearid = autogearid;
	}

	public Autogear(int autogearid, String autogearname, Set<Auto> autos) {
		this.autogearid = autogearid;
		this.autogearname = autogearname;
		this.autos = autos;
	}

	@Id
	@Column(name = "autogearid", unique = true, nullable = false)
	public int getAutogearid() {
		return this.autogearid;
	}

	public void setAutogearid(int autogearid) {
		this.autogearid = autogearid;
	}

	@Column(name = "autogearname")
	public String getAutogearname() {
		return this.autogearname;
	}

	public void setAutogearname(String autogearname) {
		this.autogearname = autogearname;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "autogear")
	public Set<Auto> getAutos() {
		return this.autos;
	}

	public void setAutos(Set<Auto> autos) {
		this.autos = autos;
	}

}
