package com.auto.jaxws.cxf.model;

// Generated Oct 12, 2014 11:01:48 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Autotire generated by hbm2java
 */
public class Autotire implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int autotireid;
	private String autotirename;
	private Set<Auto> autos = new HashSet<Auto>(0);

	public Autotire() {
	}

	public Autotire(int autotireid) {
		this.autotireid = autotireid;
	}

	public Autotire(int autotireid, String autotirename, Set<Auto> autos) {
		this.autotireid = autotireid;
		this.autotirename = autotirename;
		this.autos = autos;
	}

	public int getAutotireid() {
		return this.autotireid;
	}

	public void setAutotireid(int autotireid) {
		this.autotireid = autotireid;
	}

	public String getAutotirename() {
		return this.autotirename;
	}

	public void setAutotirename(String autotirename) {
		this.autotirename = autotirename;
	}

	public Set<Auto> getAutos() {
		return this.autos;
	}

	public void setAutos(Set<Auto> autos) {
		this.autos = autos;
	}

}
