package com.auto.jaxws.cxf.model;

// Generated Nov 16, 2014 1:40:49 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Autocategory generated by hbm2java
 */
@Entity
@Table(name = "autocategory", schema = "public")
public class Autocategory implements java.io.Serializable {

	private int categoryid;
	private String categoryname;
	private Set<Auto> autos = new HashSet<Auto>(0);

	public Autocategory() {
	}

	public Autocategory(int categoryid) {
		this.categoryid = categoryid;
	}

	public Autocategory(int categoryid, String categoryname, Set<Auto> autos) {
		this.categoryid = categoryid;
		this.categoryname = categoryname;
		this.autos = autos;
	}

	@Id
	@Column(name = "categoryid", unique = true, nullable = false)
	public int getCategoryid() {
		return this.categoryid;
	}

	public void setCategoryid(int categoryid) {
		this.categoryid = categoryid;
	}

	@Column(name = "categoryname")
	public String getCategoryname() {
		return this.categoryname;
	}

	public void setCategoryname(String categoryname) {
		this.categoryname = categoryname;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "autocategory")
	public Set<Auto> getAutos() {
		return this.autos;
	}

	public void setAutos(Set<Auto> autos) {
		this.autos = autos;
	}

}
