package com.auto.jaxws.cxf.model;

// Generated Nov 16, 2014 1:40:49 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Auto generated by hbm2java
 */
@Entity
@Table(name = "auto", schema = "public")
public class Auto implements java.io.Serializable {

	private int autoid;
	private Autorim autorim;
	private Autotire autotire;
	private Autogear autogear;
	private Autointerrior autointerrior;
	private Autocategory autocategory;
	private Autofuel autofuel;
	private Autosubcategory autosubcategory;
	private String autoname;
	private Integer automodel;
	private Double auto100km;
	private Integer autocolor;
	private Integer autokm;
	private Integer autohp;
	private Integer autohand;
	private Date autoregisterdate;
	private Integer autosold;
	private Integer autotype;
	private Double autoprice;
	private Autoproperties autoproperties;
	private Set<Autoimages> autoimageses = new HashSet<Autoimages>(0);
	private Set<Soldcars> soldcarses = new HashSet<Soldcars>(0);

	public Auto() {
	}

	public Auto(int autoid) {
		this.autoid = autoid;
	}

	public Auto(int autoid, Autorim autorim, Autotire autotire,
			Autogear autogear, Autointerrior autointerrior,
			Autocategory autocategory, Autofuel autofuel,
			Autosubcategory autosubcategory, String autoname,
			Integer automodel, Double auto100km, Integer autocolor,
			Integer autokm, Integer autohp, Integer autohand,
			Date autoregisterdate, Integer autosold, Integer autotype,
			Double autoprice, Autoproperties autoproperties,
			Set<Autoimages> autoimageses, Set<Soldcars> soldcarses) {
		this.autoid = autoid;
		this.autorim = autorim;
		this.autotire = autotire;
		this.autogear = autogear;
		this.autointerrior = autointerrior;
		this.autocategory = autocategory;
		this.autofuel = autofuel;
		this.autosubcategory = autosubcategory;
		this.autoname = autoname;
		this.automodel = automodel;
		this.auto100km = auto100km;
		this.autocolor = autocolor;
		this.autokm = autokm;
		this.autohp = autohp;
		this.autohand = autohand;
		this.autoregisterdate = autoregisterdate;
		this.autosold = autosold;
		this.autotype = autotype;
		this.autoprice = autoprice;
		this.autoproperties = autoproperties;
		this.autoimageses = autoimageses;
		this.soldcarses = soldcarses;
	}

	@Id
	@Column(name = "autoid", unique = true, nullable = false)
	public int getAutoid() {
		return this.autoid;
	}

	public void setAutoid(int autoid) {
		this.autoid = autoid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "autorim")
	public Autorim getAutorim() {
		return this.autorim;
	}

	public void setAutorim(Autorim autorim) {
		this.autorim = autorim;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "autotire")
	public Autotire getAutotire() {
		return this.autotire;
	}

	public void setAutotire(Autotire autotire) {
		this.autotire = autotire;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "autogear")
	public Autogear getAutogear() {
		return this.autogear;
	}

	public void setAutogear(Autogear autogear) {
		this.autogear = autogear;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "autointerrior")
	public Autointerrior getAutointerrior() {
		return this.autointerrior;
	}

	public void setAutointerrior(Autointerrior autointerrior) {
		this.autointerrior = autointerrior;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "autocategoryid")
	public Autocategory getAutocategory() {
		return this.autocategory;
	}

	public void setAutocategory(Autocategory autocategory) {
		this.autocategory = autocategory;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "autofuel")
	public Autofuel getAutofuel() {
		return this.autofuel;
	}

	public void setAutofuel(Autofuel autofuel) {
		this.autofuel = autofuel;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "autosubcategoryid")
	public Autosubcategory getAutosubcategory() {
		return this.autosubcategory;
	}

	public void setAutosubcategory(Autosubcategory autosubcategory) {
		this.autosubcategory = autosubcategory;
	}

	@Column(name = "autoname")
	public String getAutoname() {
		return this.autoname;
	}

	public void setAutoname(String autoname) {
		this.autoname = autoname;
	}

	@Column(name = "automodel")
	public Integer getAutomodel() {
		return this.automodel;
	}

	public void setAutomodel(Integer automodel) {
		this.automodel = automodel;
	}

	@Column(name = "auto100km", precision = 17, scale = 17)
	public Double getAuto100km() {
		return this.auto100km;
	}

	public void setAuto100km(Double auto100km) {
		this.auto100km = auto100km;
	}

	@Column(name = "autocolor")
	public Integer getAutocolor() {
		return this.autocolor;
	}

	public void setAutocolor(Integer autocolor) {
		this.autocolor = autocolor;
	}

	@Column(name = "autokm")
	public Integer getAutokm() {
		return this.autokm;
	}

	public void setAutokm(Integer autokm) {
		this.autokm = autokm;
	}

	@Column(name = "autohp")
	public Integer getAutohp() {
		return this.autohp;
	}

	public void setAutohp(Integer autohp) {
		this.autohp = autohp;
	}

	@Column(name = "autohand")
	public Integer getAutohand() {
		return this.autohand;
	}

	public void setAutohand(Integer autohand) {
		this.autohand = autohand;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "autoregisterdate", length = 13)
	public Date getAutoregisterdate() {
		return this.autoregisterdate;
	}

	public void setAutoregisterdate(Date autoregisterdate) {
		this.autoregisterdate = autoregisterdate;
	}

	@Column(name = "autosold")
	public Integer getAutosold() {
		return this.autosold;
	}

	public void setAutosold(Integer autosold) {
		this.autosold = autosold;
	}

	@Column(name = "autotype")
	public Integer getAutotype() {
		return this.autotype;
	}

	public void setAutotype(Integer autotype) {
		this.autotype = autotype;
	}

	@Column(name = "autoprice", precision = 17, scale = 17)
	public Double getAutoprice() {
		return this.autoprice;
	}

	public void setAutoprice(Double autoprice) {
		this.autoprice = autoprice;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "auto")
	public Autoproperties getAutoproperties() {
		return this.autoproperties;
	}

	public void setAutoproperties(Autoproperties autoproperties) {
		this.autoproperties = autoproperties;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "auto")
	public Set<Autoimages> getAutoimageses() {
		return this.autoimageses;
	}

	public void setAutoimageses(Set<Autoimages> autoimageses) {
		this.autoimageses = autoimageses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "auto")
	public Set<Soldcars> getSoldcarses() {
		return this.soldcarses;
	}

	public void setSoldcarses(Set<Soldcars> soldcarses) {
		this.soldcarses = soldcarses;
	}

}
