package com.auto.jaxws.cxf.model;

// Generated Nov 16, 2014 1:40:49 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Autoproperties generated by hbm2java
 */
@Entity
@Table(name = "autoproperties", schema = "public")
public class Autoproperties implements java.io.Serializable {

	private int autoid;
	private Auto auto;

	public Autoproperties() {
	}

	public Autoproperties(Auto auto) {
		this.auto = auto;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "auto"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "autoid", unique = true, nullable = false)
	public int getAutoid() {
		return this.autoid;
	}

	public void setAutoid(int autoid) {
		this.autoid = autoid;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Auto getAuto() {
		return this.auto;
	}

	public void setAuto(Auto auto) {
		this.auto = auto;
	}

}
