package com.auto.jaxws.cxf.model;

// Generated Nov 16, 2014 1:40:49 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Autotire generated by hbm2java
 */
@Entity
@Table(name = "autotire", schema = "public")
public class Autotire implements java.io.Serializable {

	private int autotireid;
	private String autotirename;
	private Set<Auto> autos = new HashSet<Auto>(0);

	public Autotire() {
	}

	public Autotire(int autotireid) {
		this.autotireid = autotireid;
	}

	public Autotire(int autotireid, String autotirename, Set<Auto> autos) {
		this.autotireid = autotireid;
		this.autotirename = autotirename;
		this.autos = autos;
	}

	@Id
	@Column(name = "autotireid", unique = true, nullable = false)
	public int getAutotireid() {
		return this.autotireid;
	}

	public void setAutotireid(int autotireid) {
		this.autotireid = autotireid;
	}

	@Column(name = "autotirename")
	public String getAutotirename() {
		return this.autotirename;
	}

	public void setAutotirename(String autotirename) {
		this.autotirename = autotirename;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "autotire")
	public Set<Auto> getAutos() {
		return this.autos;
	}

	public void setAutos(Set<Auto> autos) {
		this.autos = autos;
	}

}
