package com.auto.jaxws.cxf.model;

// Generated Nov 16, 2014 1:40:49 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Autointerrior generated by hbm2java
 */
@Entity
@Table(name = "autointerrior", schema = "public")
public class Autointerrior implements java.io.Serializable {

	private int autointerriorid;
	private String autointerriorname;
	private Set<Auto> autos = new HashSet<Auto>(0);

	public Autointerrior() {
	}

	public Autointerrior(int autointerriorid) {
		this.autointerriorid = autointerriorid;
	}

	public Autointerrior(int autointerriorid, String autointerriorname,
			Set<Auto> autos) {
		this.autointerriorid = autointerriorid;
		this.autointerriorname = autointerriorname;
		this.autos = autos;
	}

	@Id
	@Column(name = "autointerriorid", unique = true, nullable = false)
	public int getAutointerriorid() {
		return this.autointerriorid;
	}

	public void setAutointerriorid(int autointerriorid) {
		this.autointerriorid = autointerriorid;
	}

	@Column(name = "autointerriorname")
	public String getAutointerriorname() {
		return this.autointerriorname;
	}

	public void setAutointerriorname(String autointerriorname) {
		this.autointerriorname = autointerriorname;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "autointerrior")
	public Set<Auto> getAutos() {
		return this.autos;
	}

	public void setAutos(Set<Auto> autos) {
		this.autos = autos;
	}

}
