package com.auto.jaxws.cxf.model;

// Generated Nov 16, 2014 1:40:49 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Autosubcategory generated by hbm2java
 */
@Entity
@Table(name = "autosubcategory", schema = "public")
public class Autosubcategory implements java.io.Serializable {

	private int subcategoryid;
	private String subcategoryname;
	private Integer categoryid;
	private Set<Auto> autos = new HashSet<Auto>(0);

	public Autosubcategory() {
	}

	public Autosubcategory(int subcategoryid) {
		this.subcategoryid = subcategoryid;
	}

	public Autosubcategory(int subcategoryid, String subcategoryname,
			Integer categoryid, Set<Auto> autos) {
		this.subcategoryid = subcategoryid;
		this.subcategoryname = subcategoryname;
		this.categoryid = categoryid;
		this.autos = autos;
	}

	@Id
	@Column(name = "subcategoryid", unique = true, nullable = false)
	public int getSubcategoryid() {
		return this.subcategoryid;
	}

	public void setSubcategoryid(int subcategoryid) {
		this.subcategoryid = subcategoryid;
	}

	@Column(name = "subcategoryname")
	public String getSubcategoryname() {
		return this.subcategoryname;
	}

	public void setSubcategoryname(String subcategoryname) {
		this.subcategoryname = subcategoryname;
	}

	@Column(name = "categoryid")
	public Integer getCategoryid() {
		return this.categoryid;
	}

	public void setCategoryid(Integer categoryid) {
		this.categoryid = categoryid;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "autosubcategory")
	public Set<Auto> getAutos() {
		return this.autos;
	}

	public void setAutos(Set<Auto> autos) {
		this.autos = autos;
	}

}
