package com.auto.jaxws.cxf.model;

// Generated Oct 12, 2014 11:01:48 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import org.codehaus.jackson.annotate.JsonIgnore;
import org.codehaus.jackson.annotate.JsonManagedReference;

/**
 * Autofuel generated by hbm2java
 */
public class Autofuel implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int autofuelid;
	private String autofuelname;
	
	
	private Set<Auto> autos = new HashSet<Auto>(0);

	public Autofuel() {
	}

	public Autofuel(int autofuelid) {
		this.autofuelid = autofuelid;
	}

	public Autofuel(int autofuelid, String autofuelname, Set<Auto> autos) {
		this.autofuelid = autofuelid;
		this.autofuelname = autofuelname;
		this.autos = autos;
	}

	public int getAutofuelid() {
		return this.autofuelid;
	}

	public void setAutofuelid(int autofuelid) {
		this.autofuelid = autofuelid;
	}

	public String getAutofuelname() {
		return this.autofuelname;
	}

	public void setAutofuelname(String autofuelname) {
		this.autofuelname = autofuelname;
	}
	
	
	public Set<Auto> getAutos() {
		return this.autos;
	}

	public void setAutos(Set<Auto> autos) {
		this.autos = autos;
	}

}
