package com.auto.jaxws.cxf.model;

// Generated Oct 12, 2014 11:01:48 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Autosubcategory generated by hbm2java
 */
public class Autosubcategory implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int subcategoryid;
	private String subcategoryname;
	private Integer categoryid;
	private Set<Auto> autos = new HashSet<Auto>(0);

	public Autosubcategory() {
	}

	public Autosubcategory(int subcategoryid) {
		this.subcategoryid = subcategoryid;
	}

	public Autosubcategory(int subcategoryid, String subcategoryname,
			Integer categoryid, Set<Auto> autos) {
		this.subcategoryid = subcategoryid;
		this.subcategoryname = subcategoryname;
		this.categoryid = categoryid;
		this.autos = autos;
	}

	public int getSubcategoryid() {
		return this.subcategoryid;
	}

	public void setSubcategoryid(int subcategoryid) {
		this.subcategoryid = subcategoryid;
	}

	public String getSubcategoryname() {
		return this.subcategoryname;
	}

	public void setSubcategoryname(String subcategoryname) {
		this.subcategoryname = subcategoryname;
	}

	public Integer getCategoryid() {
		return this.categoryid;
	}

	public void setCategoryid(Integer categoryid) {
		this.categoryid = categoryid;
	}

	public Set<Auto> getAutos() {
		return this.autos;
	}

	public void setAutos(Set<Auto> autos) {
		this.autos = autos;
	}

}
