package com.auto.jaxws.cxf.model;

// Generated Oct 12, 2014 11:01:48 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Autocategory generated by hbm2java
 */
public class Autocategory implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int categoryid;
	private String categoryname;
	private Set<Auto> autos = new HashSet<Auto>(0);

	public Autocategory() {
	}

	public Autocategory(int categoryid) {
		this.categoryid = categoryid;
	}

	public Autocategory(int categoryid, String categoryname, Set<Auto> autos) {
		this.categoryid = categoryid;
		this.categoryname = categoryname;
		this.autos = autos;
	}

	public int getCategoryid() {
		return this.categoryid;
	}

	public void setCategoryid(int categoryid) {
		this.categoryid = categoryid;
	}

	public String getCategoryname() {
		return this.categoryname;
	}

	public void setCategoryname(String categoryname) {
		this.categoryname = categoryname;
	}

	public Set<Auto> getAutos() {
		return this.autos;
	}

	public void setAutos(Set<Auto> autos) {
		this.autos = autos;
	}

}
