package com.auto.jaxws.cxf.model;

// Generated Nov 16, 2014 1:40:49 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Autoimages generated by hbm2java
 */
@Entity
@Table(name = "autoimages", schema = "public")
public class Autoimages implements java.io.Serializable {

	private int autoimageid;
	private Auto auto;
	private String autourl;

	public Autoimages() {
	}

	public Autoimages(int autoimageid) {
		this.autoimageid = autoimageid;
	}

	public Autoimages(int autoimageid, Auto auto, String autourl) {
		this.autoimageid = autoimageid;
		this.auto = auto;
		this.autourl = autourl;
	}

	@Id
	@Column(name = "autoimageid", unique = true, nullable = false)
	public int getAutoimageid() {
		return this.autoimageid;
	}

	public void setAutoimageid(int autoimageid) {
		this.autoimageid = autoimageid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "autoid")
	public Auto getAuto() {
		return this.auto;
	}

	public void setAuto(Auto auto) {
		this.auto = auto;
	}

	@Column(name = "autourl")
	public String getAutourl() {
		return this.autourl;
	}

	public void setAutourl(String autourl) {
		this.autourl = autourl;
	}

}
