package com.auto.jaxws.cxf.model;

// Generated Oct 12, 2014 11:01:48 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Auto generated by hbm2java
 */
public class Auto implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int autoid;
	private Autogear autogear;
	private Autocategory autocategory;
	private Autosubcategory autosubcategory;
	private Autorim autorim;
	private Autointerrior autointerrior;
	private Autotire autotire;
	private Autofuel autofuel;
	private String autoname;
	private Integer automodel;
	private Double auto100km;
	private Integer autocolor;
	private Integer autokm;
	private Integer autohp;
	private Integer autohand;
	private Date autoregisterdate;
	private Integer autosold;
	private Integer autotype;
	private Double autoprice;
	private Set<Soldcars> soldcarses = new HashSet<Soldcars>(0);
	private Set<Autoimages> autoimageses = new HashSet<Autoimages>(0);

	public Auto() {
	}

	public Auto(int autoid) {
		this.autoid = autoid;
	}

	public Auto(int autoid, Autogear autogear, Autocategory autocategory,
			Autosubcategory autosubcategory, Autorim autorim,
			Autointerrior autointerrior, Autotire autotire, Autofuel autofuel,
			String autoname, Integer automodel, Double auto100km,
			Integer autocolor, Integer autokm, Integer autohp,
			Integer autohand, Date autoregisterdate, Integer autosold,
			Integer autotype, Double autoprice, Set<Soldcars> soldcarses,
			Set<Autoimages> autoimageses) {
		this.autoid = autoid;
		this.autogear = autogear;
		this.autocategory = autocategory;
		this.autosubcategory = autosubcategory;
		this.autorim = autorim;
		this.autointerrior = autointerrior;
		this.autotire = autotire;
		this.autofuel = autofuel;
		this.autoname = autoname;
		this.automodel = automodel;
		this.auto100km = auto100km;
		this.autocolor = autocolor;
		this.autokm = autokm;
		this.autohp = autohp;
		this.autohand = autohand;
		this.autoregisterdate = autoregisterdate;
		this.autosold = autosold;
		this.autotype = autotype;
		this.autoprice = autoprice;
		this.soldcarses = soldcarses;
		this.autoimageses = autoimageses;
	}

	public int getAutoid() {
		return this.autoid;
	}

	public void setAutoid(int autoid) {
		this.autoid = autoid;
	}

	public Autogear getAutogear() {
		return this.autogear;
	}

	public void setAutogear(Autogear autogear) {
		this.autogear = autogear;
	}

	public Autocategory getAutocategory() {
		return this.autocategory;
	}

	public void setAutocategory(Autocategory autocategory) {
		this.autocategory = autocategory;
	}

	public Autosubcategory getAutosubcategory() {
		return this.autosubcategory;
	}

	public void setAutosubcategory(Autosubcategory autosubcategory) {
		this.autosubcategory = autosubcategory;
	}

	public Autorim getAutorim() {
		return this.autorim;
	}

	public void setAutorim(Autorim autorim) {
		this.autorim = autorim;
	}

	public Autointerrior getAutointerrior() {
		return this.autointerrior;
	}

	public void setAutointerrior(Autointerrior autointerrior) {
		this.autointerrior = autointerrior;
	}

	public Autotire getAutotire() {
		return this.autotire;
	}

	public void setAutotire(Autotire autotire) {
		this.autotire = autotire;
	}

	public Autofuel getAutofuel() {
		return this.autofuel;
	}

	public void setAutofuel(Autofuel autofuel) {
		this.autofuel = autofuel;
	}

	public String getAutoname() {
		return this.autoname;
	}

	public void setAutoname(String autoname) {
		this.autoname = autoname;
	}

	public Integer getAutomodel() {
		return this.automodel;
	}

	public void setAutomodel(Integer automodel) {
		this.automodel = automodel;
	}

	public Double getAuto100km() {
		return this.auto100km;
	}

	public void setAuto100km(Double auto100km) {
		this.auto100km = auto100km;
	}

	public Integer getAutocolor() {
		return this.autocolor;
	}

	public void setAutocolor(Integer autocolor) {
		this.autocolor = autocolor;
	}

	public Integer getAutokm() {
		return this.autokm;
	}

	public void setAutokm(Integer autokm) {
		this.autokm = autokm;
	}

	public Integer getAutohp() {
		return this.autohp;
	}

	public void setAutohp(Integer autohp) {
		this.autohp = autohp;
	}

	public Integer getAutohand() {
		return this.autohand;
	}

	public void setAutohand(Integer autohand) {
		this.autohand = autohand;
	}

	public Date getAutoregisterdate() {
		return this.autoregisterdate;
	}

	public void setAutoregisterdate(Date autoregisterdate) {
		this.autoregisterdate = autoregisterdate;
	}

	public Integer getAutosold() {
		return this.autosold;
	}

	public void setAutosold(Integer autosold) {
		this.autosold = autosold;
	}

	public Integer getAutotype() {
		return this.autotype;
	}

	public void setAutotype(Integer autotype) {
		this.autotype = autotype;
	}

	public Double getAutoprice() {
		return this.autoprice;
	}

	public void setAutoprice(Double autoprice) {
		this.autoprice = autoprice;
	}

	public Set<Soldcars> getSoldcarses() {
		return this.soldcarses;
	}

	public void setSoldcarses(Set<Soldcars> soldcarses) {
		this.soldcarses = soldcarses;
	}

	public Set<Autoimages> getAutoimageses() {
		return this.autoimageses;
	}

	public void setAutoimageses(Set<Autoimages> autoimageses) {
		this.autoimageses = autoimageses;
	}

}
