package com.auto.jaxws.cxf.model;

// Generated Nov 16, 2014 1:40:49 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Autofuel generated by hbm2java
 */
@Entity
@Table(name = "autofuel", schema = "public")
public class Autofuel implements java.io.Serializable {

	private int autofuelid;
	private String autofuelname;
	private Set<Auto> autos = new HashSet<Auto>(0);

	public Autofuel() {
	}

	public Autofuel(int autofuelid) {
		this.autofuelid = autofuelid;
	}

	public Autofuel(int autofuelid, String autofuelname, Set<Auto> autos) {
		this.autofuelid = autofuelid;
		this.autofuelname = autofuelname;
		this.autos = autos;
	}

	@Id
	@Column(name = "autofuelid", unique = true, nullable = false)
	public int getAutofuelid() {
		return this.autofuelid;
	}

	public void setAutofuelid(int autofuelid) {
		this.autofuelid = autofuelid;
	}

	@Column(name = "autofuelname")
	public String getAutofuelname() {
		return this.autofuelname;
	}

	public void setAutofuelname(String autofuelname) {
		this.autofuelname = autofuelname;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "autofuel")
	public Set<Auto> getAutos() {
		return this.autos;
	}

	public void setAutos(Set<Auto> autos) {
		this.autos = autos;
	}

}
