package com.auto.jaxws.cxf.model;

// Generated Oct 12, 2014 11:01:48 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Customer generated by hbm2java
 */
public class Customer implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int customerid;
	private String customername;
	private Integer customerphone;
	private Integer customergender;
	private String customeradress;
	private Date customerregisterdate;
	private Set<Soldcars> soldcarses = new HashSet<Soldcars>(0);

	public Customer() {
	}

	public Customer(int customerid) {
		this.customerid = customerid;
	}

	public Customer(int customerid, String customername, Integer customerphone,
			Integer customergender, String customeradress,
			Date customerregisterdate, Set<Soldcars> soldcarses) {
		this.customerid = customerid;
		this.customername = customername;
		this.customerphone = customerphone;
		this.customergender = customergender;
		this.customeradress = customeradress;
		this.customerregisterdate = customerregisterdate;
		this.soldcarses = soldcarses;
	}

	public int getCustomerid() {
		return this.customerid;
	}

	public void setCustomerid(int customerid) {
		this.customerid = customerid;
	}

	public String getCustomername() {
		return this.customername;
	}

	public void setCustomername(String customername) {
		this.customername = customername;
	}

	public Integer getCustomerphone() {
		return this.customerphone;
	}

	public void setCustomerphone(Integer customerphone) {
		this.customerphone = customerphone;
	}

	public Integer getCustomergender() {
		return this.customergender;
	}

	public void setCustomergender(Integer customergender) {
		this.customergender = customergender;
	}

	public String getCustomeradress() {
		return this.customeradress;
	}

	public void setCustomeradress(String customeradress) {
		this.customeradress = customeradress;
	}

	public Date getCustomerregisterdate() {
		return this.customerregisterdate;
	}

	public void setCustomerregisterdate(Date customerregisterdate) {
		this.customerregisterdate = customerregisterdate;
	}

	public Set<Soldcars> getSoldcarses() {
		return this.soldcarses;
	}

	public void setSoldcarses(Set<Soldcars> soldcarses) {
		this.soldcarses = soldcarses;
	}

}
