package com.auto.jaxws.cxf.model;

// Generated Nov 16, 2014 1:40:49 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name = "customer", schema = "public")
public class Customer implements java.io.Serializable {

	private int customerid;
	private String customername;
	private Integer customerphone;
	private Integer customergender;
	private String customeradress;
	private Date customerregisterdate;
	private Set<Soldcars> soldcarses = new HashSet<Soldcars>(0);

	public Customer() {
	}

	public Customer(int customerid) {
		this.customerid = customerid;
	}

	public Customer(int customerid, String customername, Integer customerphone,
			Integer customergender, String customeradress,
			Date customerregisterdate, Set<Soldcars> soldcarses) {
		this.customerid = customerid;
		this.customername = customername;
		this.customerphone = customerphone;
		this.customergender = customergender;
		this.customeradress = customeradress;
		this.customerregisterdate = customerregisterdate;
		this.soldcarses = soldcarses;
	}

	@Id
	@Column(name = "customerid", unique = true, nullable = false)
	public int getCustomerid() {
		return this.customerid;
	}

	public void setCustomerid(int customerid) {
		this.customerid = customerid;
	}

	@Column(name = "customername")
	public String getCustomername() {
		return this.customername;
	}

	public void setCustomername(String customername) {
		this.customername = customername;
	}

	@Column(name = "customerphone")
	public Integer getCustomerphone() {
		return this.customerphone;
	}

	public void setCustomerphone(Integer customerphone) {
		this.customerphone = customerphone;
	}

	@Column(name = "customergender")
	public Integer getCustomergender() {
		return this.customergender;
	}

	public void setCustomergender(Integer customergender) {
		this.customergender = customergender;
	}

	@Column(name = "customeradress")
	public String getCustomeradress() {
		return this.customeradress;
	}

	public void setCustomeradress(String customeradress) {
		this.customeradress = customeradress;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "customerregisterdate", length = 13)
	public Date getCustomerregisterdate() {
		return this.customerregisterdate;
	}

	public void setCustomerregisterdate(Date customerregisterdate) {
		this.customerregisterdate = customerregisterdate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	public Set<Soldcars> getSoldcarses() {
		return this.soldcarses;
	}

	public void setSoldcarses(Set<Soldcars> soldcarses) {
		this.soldcarses = soldcarses;
	}

}
