package com.auto.jaxws.cxf.model;

import org.codehaus.jackson.annotate.JsonIgnore;
import org.codehaus.jackson.annotate.JsonManagedReference;

// Generated Oct 12, 2014 11:01:48 PM by Hibernate Tools 3.4.0.CR1

/**
 * Soldcars generated by hbm2java
 */
public class Soldcars implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int soldcarid;
	
	@JsonManagedReference
	private Customer customer;
	
	@JsonManagedReference
	private Auto auto;

	public Soldcars() {
	}

	public Soldcars(int soldcarid) {
		this.soldcarid = soldcarid;
	}

	public Soldcars(int soldcarid, Customer customer, Auto auto) {
		this.soldcarid = soldcarid;
		this.customer = customer;
		this.auto = auto;
	}

	public int getSoldcarid() {
		return this.soldcarid;
	}

	public void setSoldcarid(int soldcarid) {
		this.soldcarid = soldcarid;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public Auto getAuto() {
		return this.auto;
	}

	public void setAuto(Auto auto) {
		this.auto = auto;
	}

}
