package com.auto.jaxws.cxf.model;

// Generated Oct 12, 2014 11:01:48 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import org.codehaus.jackson.annotate.JsonBackReference;
import org.codehaus.jackson.annotate.JsonIgnore;
import org.codehaus.jackson.annotate.JsonManagedReference;

/**
 * Autogear generated by hbm2java
 */
public class Autogear implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int autogearid;
	private String autogearname;
	
	
	private Set<Auto> autos = new HashSet<Auto>(0);

	public Autogear() {
	}

	public Autogear(int autogearid) {
		this.autogearid = autogearid;
	}

	public Autogear(int autogearid, String autogearname, Set<Auto> autos) {
		this.autogearid = autogearid;
		this.autogearname = autogearname;
		this.autos = autos;
	}

	public int getAutogearid() {
		return this.autogearid;
	}

	public void setAutogearid(int autogearid) {
		this.autogearid = autogearid;
	}

	public String getAutogearname() {
		return this.autogearname;
	}

	public void setAutogearname(String autogearname) {
		this.autogearname = autogearname;
	}

	
	public Set<Auto> getAutos() {
		return this.autos;
	}

	public void setAutos(Set<Auto> autos) {
		this.autos = autos;
	}

}
